# syntax=docker/dockerfile:1

ARG RUBY_VERSION=4.0.2

FROM ruby:${RUBY_VERSION}-slim AS build

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      libyaml-dev \
      pkg-config \
      sqlite3 \
      libvips \
      git \
    && rm -rf /var/lib/apt/lists/*

ENV BUNDLE_PATH=/usr/local/bundle

COPY Gemfile Gemfile.lock ./

RUN bundle install && \
    rm -rf /usr/local/bundle/cache

COPY . .


FROM ruby:${RUBY_VERSION}-slim AS runtime

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      sqlite3 \
      libvips \
      curl \
    && rm -rf /var/lib/apt/lists/*

ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle

COPY --from=build /usr/local/bundle /usr/local/bundle
COPY --from=build /rails /rails

EXPOSE 3000

CMD ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]